h
ConsistencyPlus/ConsistencyPlus pull request #126
Opened 2022-07-17 16:06 UTC by IMS212

h

2022-07-17 16:08 UTC, wafflecoffee commented on fabric/build.gradle
> +    //TODO 1.19 modRuntimeOnly "maven.modrinth:suggestionproviderfabric:1.0.1"
https://modrinth.com/mod/isnrmn

2022-07-17 16:48 UTC, IMS212 commented on fabric/build.gradle
> +    //TODO 1.19 modRuntimeOnly "maven.modrinth:suggestionproviderfabric:1.0.1"
is this a direct successor?

2022-07-17 16:49 UTC, wafflecoffee commented on fabric/build.gradle
> +    //TODO 1.19 modRuntimeOnly "maven.modrinth:suggestionproviderfabric:1.0.1"
dunno but it does the exact same thing

2022-07-17 20:40 UTC, Redd56 commented
h

2022-07-17 20:50 UTC, BeansBeefBroccoli commented
![h](https://user-images.githubusercontent.com/69123018/179424282-162ae5a1-4919-4ae7-bc40-8e68e819a167.png)

2022-07-17 21:51 UTC, IMS212 commented on fabric/build.gradle
> +    //TODO 1.19 modRuntimeOnly "maven.modrinth:suggestionproviderfabric:1.0.1"
Done

2022-08-05 21:46 UTC, magneticflux- requested changes

2022-08-05 21:46 UTC, magneticflux- commented on gradle.properties
> +scrt_version_forge = 4.0.0
```suggestion
scrt_version = 4.0.0-fabric
scrt_version_forge = 4.0.0-forge
```

2022-08-05 23:38 UTC, magneticflux- commented
Bruh

Okay this patch actually fixes it:
```patch
Index: gradle.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/gradle.properties b/gradle.properties
--- a/gradle.properties	(revision ee8aa5b68d404a4564e997f77a4468396fdf80c7)
+++ b/gradle.properties	(date 1659742652922)
@@ -13,8 +13,8 @@
 
 # Api Versions
 fabric_api_version = 0.57.0+1.19
-scrt_version = 4.0.0-fabric
-scrt_version_forge = 4.0.0-forge
+scrt_version = 4.0.0
+scrt_version_forge = 4.0.0
 architectury_version = 5.7.28
 wthit_version = 5.6.1
 
Index: fabric/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/fabric/build.gradle b/fabric/build.gradle
--- a/fabric/build.gradle	(revision ee8aa5b68d404a4564e997f77a4468396fdf80c7)
+++ b/fabric/build.gradle	(date 1659742652917)
@@ -16,7 +16,7 @@
 dependencies {
     modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_version}"
     modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
-    modApi include("maven.modrinth:stonecutter_recipe_tags:${rootProject.scrt_version}")
+    modApi include("maven.modrinth:stonecutter_recipe_tags:${rootProject.scrt_version}-fabric")
     modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"
     modCompileOnly "mcp.mobius.waila:wthit-api:fabric-${rootProject.wthit_version}" // compile against the WTHIT API
     modRuntimeOnly "mcp.mobius.waila:wthit:fabric-${rootProject.wthit_version}" // run against the full jar

```

2022-08-06 01:02 UTC, closed without merging